name: Update daily tables

on:
  repository_dispatch:
    types: [daily]
  schedule:
    - cron: 0 1 * * *

jobs: 
  Daily:
    runs-on: ubuntu-latest
    env:
      RDP_S3_ENDPOINT: https://s3.amazonaws.com 
      RDP_ACCESS_KEY_ID: ${{ secrets.RDP_ACCESS_KEY_ID }}
      RDP_SECRET_ACCESS_KEY: ${{ secrets.RDP_SECRET_ACCESS_KEY }}
      AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies ...
        run: pip3 install -r requirements.txt

      # - name: Update daily_borough_poivisits_by_sector ...
      #   run: ./sg run --name daily_borough_poivisits_by_sector
      
      # - name: Update daily_borough_poivisits_by_subsector ...
      #   run: ./sg run --name daily_borough_poivisits_by_subsector

      - name: Update daily_nyc_poivisits ...
        run: ./sg run --name daily_nyc_poivisits_202107

      # - name: Update daily_zip_poivisits_by_sector ...
      #   run: ./sg run --name daily_zip_poivisits_by_sector
      
      # - name: Update daily_zip_poivisits_by_subsector ...
      #   run: ./sg run --name daily_zip_poivisits_by_subsector

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          mention_users: 'U01RHB6SAQ5,U01J189FNNP'
          mention_users_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}