name: Test S3 bucket sync

on:
  workflow_dispatch:

jobs: 
  Sync:
    runs-on: ubuntu-latest
    env:
      RDP_S3_ENDPOINT: https://s3.amazonaws.com 
      RDP_ACCESS_KEY_ID: ${{ secrets.RDP_ACCESS_KEY_ID }}
      RDP_SECRET_ACCESS_KEY: ${{ secrets.RDP_SECRET_ACCESS_KEY }}
      SG_S3_ENDPOINT: https://s3.wasabisys.com
      SG_ACCESS_KEY_ID: ${{ secrets.SG_ACCESS_KEY_ID }}
      SG_SECRET_ACCESS_KEY: ${{ secrets.SG_SECRET_ACCESS_KEY }}
      AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies ...
        run: |
          pip3 install -r requirements.txt
          curl -O https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2020-06-26T19-56-55Z
          mv mc.RELEASE.2020-06-26T19-56-55Z mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add sg $SG_S3_ENDPOINT $SG_ACCESS_KEY_ID $SG_SECRET_ACCESS_KEY --api S3v4
          mc config host add rdp $RDP_S3_ENDPOINT $RDP_ACCESS_KEY_ID $RDP_SECRET_ACCESS_KEY --api S3v4
        
      # - name: Sync Core POI Test ...
      #   run: ./sg sync --name core_poi_test
      - name: Update weekly patterns NYC ...
        run: ./sg run --name wp_nyc_202107
      # - name: Sync Neighborhood Patterns Test ...
      #   run: ./sg sync --name neighborhood_patterns