name: S3 bucket sync

on:
  repository_dispatch:
    types: [sync]
  schedule:
    - cron: 0 0 * * *

jobs: 
  Sync:
    runs-on: ubuntu-latest
    env:
      RDP_S3_ENDPOINT: https://s3.amazonaws.com 
      RDP_ACCESS_KEY_ID: ${{ secrets.RDP_ACCESS_KEY_ID }}
      RDP_SECRET_ACCESS_KEY: ${{ secrets.RDP_SECRET_ACCESS_KEY }}
      SG_S3_ENDPOINT: https://s3.wasabisys.com
      SG_ACCESS_KEY_ID: ${{ secrets.SG_ACCESS_KEY_ID }}
      SG_SECRET_ACCESS_KEY: ${{ secrets.SG_SECRET_ACCESS_KEY }}
      AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies ...
        run: |
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add sg $SG_S3_ENDPOINT $SG_ACCESS_KEY_ID $SG_SECRET_ACCESS_KEY --api S3v4
          mc config host add rdp $RDP_S3_ENDPOINT $RDP_ACCESS_KEY_ID $RDP_SECRET_ACCESS_KEY --api S3v4

      - name: Sync Core POI ...
        working-directory: _sync
        run: ./core_poi.sh
      
      - name: Sync Social Distancing ...
        working-directory: _sync
        run: ./social_distancing.sh

      - name: Sync Weekly Patterns ...
        working-directory: _sync
        run: ./weekly_patterns.sh

      - name: Repair Tables ...
        working-directory: _sync
        run: python3 repair_tables.py